server:
  port: 10086
spring:
  application:
    name: ly-registry
eureka:
  client:
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:10087/eureka

    #register-with-eureka: false #不注册  # 是否注册自己的信息到EurekaServer，默认是true
    #fetch-registry: false    #不拉取   # 是否拉取其它服务的信息，默认是true
    #fetch-registry: false
    #register-with-eureka: false

