server:
  port: 10011
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

zuul:
  prefix:  /gateway #添加路由前缀
  routes:
    item-service: #/item/**

    upload-service:
      path: /upload/**
      #serviceId: upload-service
      #strip-prefix: false
  ignored-services:
    - upload-service # 忽略upload-service服务
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #熔断超时时长：5000ms
ribbon:
  ConnectTimeout: 1000 #ribbon链接超时时长
  ReadTimeout: 3500 #ribbon读取超时时长
  MaxAutoRetries: 0 #当前服务重试次数
  MaxAutoRetriesNextServer: 0 #切换服务重试次数
#ribbon:
  #ConnectTimeout: 250 # Ribbon的连接超时时间
  #ReadTimeout: 1000 # Ribbon的数据读取超时时间
  #OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
  #MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
  #MaxAutoRetries: 1 # 对当前实例的重试次数